### GENERAL SETTINGS ###

# Site settings
title: DEKOLOR MM COLOMBIA
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/dekolor" #important: start with /
url: "http://fgleyze.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

css:
  container_padding: "15px"

### CONTACT SETTINGS ###

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - "Calle 97, 22#25"
    - "Bogot치, Colombia"
email: hello@solidtheme.com
tel: +34 8493-4893

# Companies information. Shown on Home.
companies:
  - name: Dynamo Playgrounds
    img: logo_dynamo_playgrounds.png
  - name: Corocord
    img: logo_corocord.png
  - name: Rhino
    img: logo_rhino.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Nuestra empresa fue creada para dar soluciones de recreaci칩n urbana publica y privada, con un objetivo importante: crear espacios recreativos para ni침os y j칩venes, innovadores, de calidad y seguros."
